save path: C:\Users\screa\AppData\Roaming\Macromedia\Flash Player\#SharedObjects\532RR5BF\localhost\Programs\Steam\steamapps\common\NEO
  Scavenger\NEOScavenger.exe\nsSGv1.sol
quicksave count: 3
autosave count: 3
autosave interval: 2
