CONFIG_PATH = "config.yaml"

#Names for the configuration fields.
PATH_VAR_NAME = "save path"
QUICKSAVE_COUNT_VAR_NAME = "quicksave count"
AUTOSAVE_COUNT_VAR_NAME = "autosave count"
AUTOSAVE_INTERVAL_VAR_NAME = "autosave interval"

DIVIDER_WIDTH = 75

#Directory names
QUICKSAVE_DIR_NAME = "quicksaves"
AUTOSAVE_DIR_NAME = "autosaves"
NEEDED_DIRS = [QUICKSAVE_DIR_NAME, AUTOSAVE_DIR_NAME]

#GUI keys
SAVEFILE_PATH_KEY = "-SAVEFILE_PATH-"
CHANGE_SAVEFILE_PATH_KEY = "-CHANGE_SAVEFILE_PATH-"
QUICKSAVE_KEY = "-QUICKSAVE-"
LOAD_LAST_QUICKSAVE_KEY = "-LOAD_LAST_QUICKSAVE-"
CHOOSE_QUICKSAVE_LOAD_KEY = "-CHOOSE_QUICKSAVE_LOAD-"